# Generated by Django 5.2.15 on 2026-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softstu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='图书编号')),
                ('title', models.CharField(max_length=100, verbose_name='书名')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
